### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by MaximeDelhorme** [nuruddinsyah/need_resume#3]
Hi,

Is there any plan to migrate the package to null safety?
Thanks!

**Comment by nuruddinsyah** [comment]
Yes! there will be plan to migrate to null safety for the next release.
Thanks @MaximeDelhorme

**Comment by nuruddinsyah** [comment]
Hi, @MaximeDelhorme

Yes! there will be plan to migrate to null safety for the next release.
Thanks.

**Comment by nuruddinsyah** [comment]
Done, @MaximeDelhorme. Check it out :) https://github.com/nuruddinsyah/need_resume/commit/914151fa8197d8721f7ab9c73ea08bd7b5a9ad31
[https://pub.dev/packages/need_resume](https://pub.dev/packages/need_resume)

**Comment by MaximeDelhorme** [comment]
Thanks!
