### ISSUE TITLE
Errors after upgrading Flutter to 3.0

### ISSUE THREAD

**Issue by javaherisaber** [nuruddinsyah/need_resume#4]
When building a project with Flutter 3.0 there are errors like these:
```
/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/need_resume-1.0.6/lib/need_resume.dart:80:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/sdk/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/C:/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/need_resume-1.0.6/lib/need_resume.dart:81:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/sdk/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) => onReady());
                   ^
/C:/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/need_resume-1.0.6/lib/need_resume.dart:86:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/sdk/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
```

**Comment by nuruddinsyah** [comment]
Thank you for reporting this issue, @javaherisaber!

I'll fix and update the library as soon as possible. The issue is caused by a simplification of the API, the `instance` property on bindings is now non-nullable in Flutter 3.0.0+, as per [Flutter 3.0.0 release notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) page.

Regards,
Faruq Nuruddinsyah.

**Comment by vohoangtuit** [comment]
get class Resume and  ResumableState from lib, pass into your project and use them

**Comment by rsbthebest** [comment]
Has there been any update on this?

**Comment by javaherisaber** [comment]
@rsbthebest @vohoangtuit 
Since there was no update to remove this annoying error, I'm using this package now:

https://pub.dev/packages/lifecycle_aware_state

**Comment by nuruddinsyah** [comment]
Hi everyone! I'm really sorry to have kept you all waiting long. I got a lot of stuff to do lately.

I have updated the library to version 1.0.7. Thank you.
